# Generated by Django 5.0.3 on 2024-07-01 10:04

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogpage', '0003_alter_blog_cover_image_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='contents',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
