# Generated by Django 5.0.3 on 2024-07-01 10:16

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogpage', '0004_alter_blog_contents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='contents',
            field=django_ckeditor_5.fields.CKEditor5Field(),
        ),
    ]
