# Generated by Django 5.0.3 on 2024-07-06 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogpage', '0005_alter_blog_contents'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='created_date',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='comments',
            old_name='blog',
            new_name='post',
        ),
        migrations.RenameField(
            model_name='comments',
            old_name='comment',
            new_name='text',
        ),
        migrations.AddField(
            model_name='comments',
            name='email',
            field=models.EmailField(default=0, max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comments',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
